deck = [
    # BOISSON
    {"id": 1, "text": "Les gars boivent", "category": "boisson"},
    {"id": 2, "text": "Les filles boivent", "category": "boisson"},
    {"id": 3, "text": "Drinking race !", "category": "boisson"},
    {"id": 4, "text": "Prend un SHOT!", "category": "boisson"},
    {"id": 5, "text": "Donne deux gorgées", "category": "boisson"},
    {"id": 6, "text": "Ta gauche et ta droite boivent", "category": "boisson"},
    {"id": 7, "text": "Celui qui a le moins bu termine sa boisson", "category": "boisson"},
    {"id": 8, "text": "finis ta boisson !", "category": "boisson"},
    {"id": 9, "text": "Gorgée générale !", "category": "boisson"},
    {"id": 10, "text": "[player] prend une gorgée", "category": "boisson"},
    {"id": 11, "text": "[player] donne 2 shots", "category": "boisson"},
    {"id": 12, "text": "Ceux en couple boivent", "category": "boisson"},
    {"id": 37, "text": "[player] peux donner de 1 à 10 gorgées à [random]", "category": "défi"},

    # PARLER
    {"id": 13, "text": "Quel est le truc le plus BDSM que tu as fait ?", "category": "parler"},
    {"id": 14, "text": "Raconte ta pire annectode de sexe", "category": "parler"},
    {"id": 15, "text": "Selon toi... qui est le moins bien habillé dans la pièce ?", "category": "parler"},
    {"id": 16, "text": "Si tu devais changer de vie avec une personne dans la piece ce serait qui ?", "category": "parler"},
    {"id": 17, "text": "Excepté ton partenaire avec qui sortirais-tu dans la pièce ?", "category": "parler"},
    {"id": 18, "text": "[player] quel est ton plus grand fantasme ?", "category": "parler"},
    {"id": 19, "text": "Avec qui voudrais-tu le moins être en couple dans la pièce ?", "category": "parler"},
    {"id": 20, "text": "[player] pose la question de ton choix à la personnne de ton choix", "category": "parler"},
    {"id": 21, "text": "Qui appellerais tu dans la pièce pour t'aider à cacher un corps ?", "category": "parler"},
    {"id": 22, "text": "Quelle est ta pire perte d'argent ?", "category": "parler"},
    {"id": 23, "text": "À quand remonte ton dernier orgasme ?", "category": "parler"},
    {"id": 24, "text": "Quel est le truc le plus illégal que tu as fait ?", "category": "parler"},

    # DÉFI
    {"id": 25, "text": "Change un bout de vêtement avec la personne en face", "category": "défi"},
    {"id": 26, "text": "Avale un oeuf cru", "category": "défi"},
    {"id": 27, "text": "La personne de ton choix te fait un belly shot", "category": "défi"},
    {"id": 28, "text": "Drink un shot ! mystère", "category": "défi"},
    {"id": 29, "text": "Laisse les gens texter à une personne avec ton cell (pas le droit de supprimer avant demain)", "category": "défi"},
    {"id": 30, "text": "Sort dehors deux bonnes minutes", "category": "défi"},
    {"id": 31, "text": "Laisse les gens fouiller dans ton cell 2 bonnes minutes", "category": "défi"},
    {"id": 32, "text": "Kiss ton partenaire en ayant une gorgée (Transfert la)", "category": "défi"},
    {"id": 33, "text": "Fais un tour de la bâtisse. Pas le droit de mettre un manteau ou des bottes", "category": "défi"},
    {"id": 34, "text": "Enlève un bout de vêtement", "category": "défi"},
    {"id": 35, "text": "Fait 15 push-up 💪", "category": "défi"},
    {"id": 36, "text": "Appel le dernier numéro à qui tu as parlé (1 minute minimum)", "category": "défi"},
    {"id": 37, "text": "[player] doit faire un massage à [random]", "category": "défi"},

    # DIVERS
    {"id": 38, "text": "Votons ! La personne qui déçoit le plus ses parents boit", "category": "divers"},
    {"id": 39, "text": "Votons ! Le plus résistant à l'alcool finit sa boisson", "category": "divers"},
    {"id": 40, "text": "On prend un selfie tout le monde ensemble", "category": "divers"},
    {"id": 41, "text": "Jeu de la carte bisou", "category": "divers"},
    {"id": 42, "text": "Le plus susceptible de juger les gens selon leur signe astrologique", "category": "divers"},
    {"id": 43, "text": "Tout le monde change de place", "category": "divers"},
    {"id": 44, "text": "Votons ! Le plus saoul donne sa consommation", "category": "divers"},
    {"id": 45, "text": "Le plus susceptible d'avoir un nom pour son entre jambes boit", "category": "divers"},
    {"id": 46, "text": "Tout le monde doit répondre à la première story", "category": "divers"},
    {"id": 47, "text": "Rebrasse le deck au complet 😱", "category": "divers", "effect": "shuffleDeck"},
    #{ "id": 48, "text": "Refais jouer une carte déjà jouée et choisie la victime", "category": "divers" },
]